name: Bug report
description: Create a report to help us improve
title: '[BUG]: <title> '
labels: ["bug"]
body:
- type: markdown
    attributes:
      value:
      "### Please fill this form to report the bug you encountered with the Puter AI PWA."
- type: textarea
  id: description
  attributes:
    label: "Bug description"
    description: "A clear and concise description of what the bug is."
    placeholder: "When i... it bugs and..."
  validations:
    required: true
- type: textarea
  id: reproduce
  attributes:
    label: To reproduce
    description: An explanation of how to reproduce the bug
    value : |
      1.
      2.
      3.
  validations:
    required: true
- type: textarea
  id: expected_behavior
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help explain your problem.
    placeholder: Use the image button in the Markdown bar to add screenshots
  validations:
    required: false
- type: dropdown
  id: platform
  attributes:
    label: Platform
    description: Select the platform on which you encountered the bug
    options:
      - Computer
      - Smartphone
    default: 0
  validations:
    required: true
- type: dropdown
  id: operating_system
  attributes:
    label: Operating system
    description: Select the operating system on which you encountered the bug
    options:
      - Windows
      - MacOS
      - Linux
      - Android
      - iOS
      - FreeBSD
      - Other
    default: 0
  validations:
    required: true
- type: dropdown
  id: browser
  attributes:
    label: Browser
    description: Select the browser you were using when you encountered the bug
    options:
      - Chrome
      - Firefox
      - Edge
      - Safari
      - Opera
      - Arc
      - Other chromium-based browser
      - Other something-else-based browser
    default: 0
  validations:
    required: true
- type: textarea
  id: additional_context
  attributes:
    label: Additional context
    description: Add any other context about the problem here.
  validations:
    required: false
- type: imput
  id: version
  attributes:
    label: PWA version
    description: Type the version of the Puter AI PWA on which you encountered the bug
    placeholder: Go to the settings, and look at the version number on the page, and copy & paste the version number here.
  validations:
    required: true
